/** CAN message encoder/decoder: automatically generated - do not edit
  * Generated by dbcc: See https://github.com/howerj/dbcc */
#ifndef KSU_DBC_H
#define KSU_DBC_H

/* If the contents of this file have caused breaking changes for you, you could try using
   an older version of the generator. You can specify this on the command line with
   the -n option. */
#define DBCC_GENERATOR_VERSION (3)

#include <stdint.h>
#include <stdio.h>

#ifdef __cplusplus
extern "C" { 
#endif

#ifndef PREPACK
#define PREPACK
#endif

#ifndef POSTPACK
#define POSTPACK
#endif

#ifndef DBCC_TIME_STAMP
#define DBCC_TIME_STAMP
typedef uint32_t dbcc_time_stamp_t; /* Time stamp for message; you decide on units */
#endif

#ifndef DBCC_STATUS_ENUM
#define DBCC_STATUS_ENUM
typedef enum {
	DBCC_SIG_STAT_UNINITIALIZED_E = 0, /* Message never sent/received */
	DBCC_SIG_STAT_OK_E            = 1, /* Message ok */
	DBCC_SIG_STAT_ERROR_E         = 2, /* Encode/Decode/Timestamp/Any error */
} dbcc_signal_status_e;
#endif

#define CAN_ID_SEGMENT1_TEMPS1 (26) /* 0x1a */
#define CAN_ID_SEGMENT1_TEMPS2 (27) /* 0x1b */
#define CAN_ID_SEGMENT2_TEMPS1 (42) /* 0x2a */
#define CAN_ID_SEGMENT2_TEMPS2 (43) /* 0x2b */
#define CAN_ID_SEGMENT3_TEMPS1 (58) /* 0x3a */
#define CAN_ID_SEGMENT3_TEMPS2 (59) /* 0x3b */
#define CAN_ID_SEGMENT4_TEMPS1 (74) /* 0x4a */
#define CAN_ID_SEGMENT4_TEMPS2 (75) /* 0x4b */
#define CAN_ID_SEGMENT5_TEMPS1 (90) /* 0x5a */
#define CAN_ID_SEGMENT5_TEMPS2 (91) /* 0x5b */
#define CAN_ID_SEGMENT6_TEMPS1 (106) /* 0x6a */
#define CAN_ID_SEGMENT6_TEMPS2 (107) /* 0x6b */
#define CAN_ID_M160_TEMPERATURE_SET_1 (160) /* 0xa0 */
#define CAN_ID_M161_TEMPERATURE_SET_2 (161) /* 0xa1 */
#define CAN_ID_M162_TEMPERATURE_SET_3 (162) /* 0xa2 */
#define CAN_ID_M163_ANALOG_INPUT_VOLTAGES (163) /* 0xa3 */
#define CAN_ID_M164_DIGITAL_INPUT_STATUS (164) /* 0xa4 */
#define CAN_ID_M165_MOTOR_POSITION_INFO (165) /* 0xa5 */
#define CAN_ID_M166_CURRENT_INFO (166) /* 0xa6 */
#define CAN_ID_M167_VOLTAGE_INFO (167) /* 0xa7 */
#define CAN_ID_M168_FLUX_ID_IQ_INFO (168) /* 0xa8 */
#define CAN_ID_M169_INTERNAL_VOLTAGES (169) /* 0xa9 */
#define CAN_ID_M170_INTERNAL_STATES (170) /* 0xaa */
#define CAN_ID_M171_FAULT_CODES (171) /* 0xab */
#define CAN_ID_M172_TORQUE_AND_TIMER_INFO (172) /* 0xac */
#define CAN_ID_M173_MODULATION_AND_FLUX_INFO (173) /* 0xad */
#define CAN_ID_M174_FIRMWARE_INFO (174) /* 0xae */
#define CAN_ID_M175_DIAG_DATA (175) /* 0xaf */
#define CAN_ID_M192_COMMAND_MESSAGE (192) /* 0xc0 */
#define CAN_ID_M193_READ_WRITE_PARAM_COMMAND (193) /* 0xc1 */
#define CAN_ID_M194_READ_WRITE_PARAM_RESPONSE (194) /* 0xc2 */
#define CAN_ID_VCU_STATUS (195) /* 0xc3 */
#define CAN_ID_VCU_PEDAL_READINGS (196) /* 0xc4 */
#define CAN_ID_DAQ_SHOCKPOTS (197) /* 0xc5 */
#define CAN_ID_VCU_WHEELSPEED_READINGS (198) /* 0xc6 */
#define CAN_ID_VCU_FIRMWARE_VERSION (200) /* 0xc8 */
#define CAN_ID_DASH_BUTTONS (235) /* 0xeb */
#define CAN_ID_M188_U2C_MESSAGE_RXD (469) /* 0x1d5 */
#define CAN_ID_M187_U2C_COMMAND_TXD (471) /* 0x1d7 */
#define CAN_ID_BMS_CURRENT_LIMIT (514) /* 0x202 */
#define CAN_ID_MSGID_0X6B1 (1713) /* 0x6b1 */
#define CAN_ID_MSGID_0X6B2 (1714) /* 0x6b2 */
#define CAN_ID_MSGID_0X6B3 (1715) /* 0x6b3 */

/* raw ADC voltage reading of module1 cells 1-6 */
typedef PREPACK struct {
	uint8_t cell2temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell3temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell4temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell5temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell6temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t mintemp1to6; /* scaling 0.0, offset 0.0, units none  */
	uint8_t maxtemp1to6; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell1temp; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x01a_segment1_temps1_t;

/* raw ADC voltage reading of module1 cells 6-12 */
typedef PREPACK struct {
	uint8_t cell8temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell9temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell10temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell11temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell12temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t mintemp7to12; /* scaling 0.0, offset 0.0, units none  */
	uint8_t maxtemp7to12; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell7temp; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x01b_segment1_temps2_t;

/* raw ADC voltage reading of module2 cells 1-6 */
typedef PREPACK struct {
	uint8_t cell14temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell15temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell16temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell17temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell18temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t mintemp13to18; /* scaling 0.0, offset 0.0, units none  */
	uint8_t maxtemp13to18; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell13temp; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x02a_segment2_temps1_t;

/* raw ADC voltage reading of module2 cells 6-12 */
typedef PREPACK struct {
	uint8_t cell20temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell21temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell22temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell23temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell24temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t mintemp19to24; /* scaling 0.0, offset 0.0, units none  */
	uint8_t maxtemp19to24; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell19temp; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x02b_segment2_temps2_t;

/* raw ADC voltage reading of module3 cells 1-6 */
typedef PREPACK struct {
	uint8_t cell26temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell27temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell28temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell29temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell30temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t mintemp25to30; /* scaling 0.0, offset 0.0, units none  */
	uint8_t maxtemp25to30; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell25temp; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x03a_segment3_temps1_t;

/* raw ADC voltage reading of module3 cells 6-12 */
typedef PREPACK struct {
	uint8_t cell32temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell33temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell34temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell35temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell36temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t mintemp31to36; /* scaling 0.0, offset 0.0, units none  */
	uint8_t maxtemp31to36; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell31temp; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x03b_segment3_temps2_t;

/* raw ADC voltage reading of module4 cells 1-6 */
typedef PREPACK struct {
	uint8_t cell38temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell39temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell40temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell41temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell42temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t mintemp37to42; /* scaling 0.0, offset 0.0, units none  */
	uint8_t maxtemp37to42; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell37temp; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x04a_segment4_temps1_t;

/* raw ADC voltage reading of module4 cells 6-12 */
typedef PREPACK struct {
	uint8_t cell44temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell45temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell46temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell47temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell48temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t mintemp43to48; /* scaling 0.0, offset 0.0, units none  */
	uint8_t maxtemp43to48; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell43temp; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x04b_segment4_temps2_t;

/* raw ADC voltage reading of module5 cells 1-6 */
typedef PREPACK struct {
	uint8_t cell50temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell51temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell52temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell53temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell54temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t mintemp49to54; /* scaling 0.0, offset 0.0, units none  */
	uint8_t maxtemp49to54; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell49temp; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x05a_segment5_temps1_t;

/* raw ADC voltage reading of module5 cells 6-12 */
typedef PREPACK struct {
	uint8_t cell56temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell57temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell58temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell59temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell60temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t mintemp55to60; /* scaling 0.0, offset 0.0, units none  */
	uint8_t maxtemp55to60; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell55temp; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x05b_segment5_temps2_t;

/* raw ADC voltage reading of module6 cells 1-6 */
typedef PREPACK struct {
	uint8_t cell62temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell63temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell64temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell65temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell66temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t mintemp61to66; /* scaling 0.0, offset 0.0, units none  */
	uint8_t maxtemp61to66; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell61temp; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x06a_segment6_temps1_t;

/* raw ADC voltage reading of module6 cells 6-12 */
typedef PREPACK struct {
	uint8_t cell68temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell69temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell70temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell71temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell72temp; /* scaling 0.0, offset 0.0, units none  */
	uint8_t mintemp67to72; /* scaling 0.0, offset 0.0, units none  */
	uint8_t maxtemp67to72; /* scaling 0.0, offset 0.0, units none  */
	uint8_t cell67temp; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x06b_segment6_temps2_t;

typedef PREPACK struct {
	int16_t D2_Module_B; /* scaling 0.1, offset 0.0, units none  */
	int16_t D3_Module_C; /* scaling 0.1, offset 0.0, units none  */
	int16_t D4_Gate_Driver_Board; /* scaling 0.1, offset 0.0, units none  */
	int16_t D1_Module_A; /* scaling 0.1, offset 0.0, units none  */
} POSTPACK can_0x0a0_M160_Temperature_Set_1_t;

typedef PREPACK struct {
	int16_t D2_RTD1_Temperature; /* scaling 0.1, offset 0.0, units none  */
	int16_t D3_RTD2_Temperature; /* scaling 0.1, offset 0.0, units none  */
	int16_t D4_RTD3_Temperature; /* scaling 0.1, offset 0.0, units none  */
	int16_t D1_Control_Board_Temperature; /* scaling 0.1, offset 0.0, units none  */
} POSTPACK can_0x0a1_M161_Temperature_Set_2_t;

typedef PREPACK struct {
	int16_t D2_RTD5_Temperature; /* scaling 0.1, offset 0.0, units none  */
	int16_t D3_Motor_Temperature; /* scaling 0.1, offset 0.0, units none  */
	int16_t D4_Torque_Shudder; /* scaling 0.1, offset 0.0, units none  */
	int16_t D1_RTD4_Temperature; /* scaling 0.1, offset 0.0, units none  */
} POSTPACK can_0x0a2_M162_Temperature_Set_3_t;

/*  */
typedef PREPACK struct {
	uint16_t D2_Analog_Input_2; /* scaling 0.0, offset 0.0, units none  */
	uint16_t D3_Analog_Input_3; /* scaling 0.0, offset 0.0, units none  */
	uint16_t D4_Analog_Input_4; /* scaling 0.0, offset 0.0, units none  */
	uint16_t D5_Analog_Input_5; /* scaling 0.0, offset 0.0, units none  */
	uint16_t D6_Analog_Input_6; /* scaling 0.0, offset 0.0, units none  */
	uint16_t D1_Analog_Input_1; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x0a3_M163_Analog_Input_Voltages_t;

typedef PREPACK struct {
	uint8_t D2_Digital_Input_2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D3_Digital_Input_3; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D4_Digital_Input_4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D5_Digital_Input_5; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D6_Digital_Input_6; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D7_Digital_Input_7; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D8_Digital_Input_8; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D1_Digital_Input_1; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x0a4_M164_Digital_Input_Status_t;

typedef PREPACK struct {
	int16_t D2_Motor_Speed; /* scaling 1.0, offset 0.0, units none  */
	int16_t D3_Electrical_Output_Frequency; /* scaling 0.1, offset 0.0, units none  */
	int16_t D4_Delta_Resolver_Filtered; /* scaling 0.1, offset 0.0, units none  */
	uint16_t D1_Motor_Angle_Electrical; /* scaling 0.1, offset 0.0, units none  */
} POSTPACK can_0x0a5_M165_Motor_Position_Info_t;

typedef PREPACK struct {
	int16_t D2_Phase_B_Current; /* scaling 0.1, offset 0.0, units none  */
	int16_t D3_Phase_C_Current; /* scaling 0.1, offset 0.0, units none  */
	int16_t D4_DC_Bus_Current; /* scaling 0.1, offset 0.0, units none  */
	int16_t D1_Phase_A_Current; /* scaling 0.1, offset 0.0, units none  */
} POSTPACK can_0x0a6_M166_Current_Info_t;

typedef PREPACK struct {
	int16_t D2_Output_Voltage; /* scaling 0.1, offset 0.0, units none  */
	int16_t D3_VAB_Vd_Voltage; /* scaling 0.1, offset 0.0, units none  */
	int16_t D4_VBC_Vq_Voltage; /* scaling 0.1, offset 0.0, units none  */
	int16_t D1_DC_Bus_Voltage; /* scaling 0.1, offset 0.0, units none  */
} POSTPACK can_0x0a7_M167_Voltage_Info_t;

typedef PREPACK struct {
	int16_t D2_Flux_Feedback; /* scaling 0.0, offset 0.0, units none  */
	int16_t D3_Id; /* scaling 0.1, offset 0.0, units none  */
	int16_t D4_Iq; /* scaling 0.1, offset 0.0, units none  */
	int16_t D1_Flux_Command; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x0a8_M168_Flux_ID_IQ_Info_t;

typedef PREPACK struct {
	int16_t D2_Reference_Voltage_2_5; /* scaling 0.0, offset 0.0, units none  */
	int16_t D3_Reference_Voltage_5_0; /* scaling 0.0, offset 0.0, units none  */
	int16_t D4_Reference_Voltage_12_0; /* scaling 0.0, offset 0.0, units none  */
	int16_t D1_Reference_Voltage_1_5; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x0a9_M169_Internal_Voltages_t;

typedef PREPACK struct {
	uint16_t D1_VSM_State; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D2_Inverter_State; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D4_Inverter_Discharge_State; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D3_Relay_3_Status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D3_Relay_1_Status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D3_Relay_5_Status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D3_Relay_6_Status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D4_Inverter_Run_Mode; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D3_Relay_4_Status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D3_Relay_2_Status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D5_Inverter_Command_Mode; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D6_Inverter_Enable_State; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D6_Inverter_Enable_Lockout; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D7_Direction_Command; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D7_BMS_Active; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D7_BMS_Torque_Limiting; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x0aa_M170_Internal_States_t;

typedef PREPACK struct {
	uint16_t D2_Post_Fault_Hi; /* scaling 1.0, offset 0.0, units none  */
	uint16_t D3_Run_Fault_Lo; /* scaling 1.0, offset 0.0, units none  */
	uint16_t D4_Run_Fault_Hi; /* scaling 1.0, offset 0.0, units none  */
	uint16_t D1_Post_Fault_Lo; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x0ab_M171_Fault_Codes_t;

typedef PREPACK struct {
	uint32_t D3_Power_On_Timer; /* scaling 0.0, offset 0.0, units none  */
	int16_t D2_Torque_Feedback; /* scaling 0.1, offset 0.0, units none  */
	int16_t D1_Commanded_Torque; /* scaling 0.1, offset 0.0, units none  */
} POSTPACK can_0x0ac_M172_Torque_And_Timer_Info_t;

typedef PREPACK struct {
	int16_t D2_Flux_Weakening_Output; /* scaling 0.1, offset 0.0, units none  */
	int16_t D3_Id_Command; /* scaling 0.1, offset 0.0, units none  */
	int16_t D4_Iq_Command; /* scaling 0.1, offset 0.0, units none  */
	int16_t D1_Modulation_Index; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x0ad_M173_Modulation_And_Flux_Info_t;

typedef PREPACK struct {
	uint16_t D2_SW_Version; /* scaling 1.0, offset 0.0, units none  */
	uint16_t D3_DateCode_MMDD; /* scaling 1.0, offset 0.0, units none  */
	uint16_t D4_DateCode_YYYY; /* scaling 1.0, offset 0.0, units none  */
	uint16_t D1_Project_Code_EEP_Ver; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x0ae_M174_Firmware_Info_t;

typedef PREPACK struct {
	int16_t D4_Diag_Data_2; /* scaling 1.0, offset 0.0, units none  */
	int16_t D3_Diag_Data_1; /* scaling 1.0, offset 0.0, units none  */
	int16_t D5_Diag_Data_3; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D2_Buffer_Segment; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D1_Buffer_Record; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x0af_M175_Diag_Data_t;

/* The command message is used to transmit data to the controller. This message is sent from a user supplied external controller to the PMxxx controller. */
typedef PREPACK struct {
	int16_t Speed_Command; /* scaling 1.0, offset 0.0, units none  */
	int16_t Torque_Limit_Command; /* scaling 0.1, offset 0.0, units none  */
	int16_t Torque_Command; /* scaling 0.1, offset 0.0, units none  */
	uint8_t Inverter_Discharge; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Speed_Mode_Enable; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Inverter_Enable; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Direction_Command; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x0c0_M192_Command_Message_t;

/* To write a parameter use message 0x0C1 with byte #2 set to 1 (write). 
To read a parameter use message 0x0C1 with byte #2 to set 0 (read).  */
typedef PREPACK struct {
	int16_t D3_Data_Command; /* scaling 1.0, offset 0.0, units none  */
	uint16_t D1_Parameter_Address_Command; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D2_Read_Write_Command; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x0c1_M193_Read_Write_Param_Command_t;

/* To write a parameter use message 0x0C1 with byte #2 set to 1 (write). 
To read a parameter use message 0x0C1 with byte #2 to set 0 (read).  */
typedef PREPACK struct {
	int16_t D3_Data_Response; /* scaling 1.0, offset 0.0, units none  */
	uint16_t D1_Parameter_Address_Response; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D2_Write_Success; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x0c2_M194_Read_Write_Param_Response_t;

typedef PREPACK struct {
	uint16_t DISTANCE_TRAVELLED; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ECU_STATES; /* scaling 1.0, offset 0.0, units none  */
	uint8_t MAX_TORQUE; /* scaling 1.0, offset 0.0, units none  */
	uint8_t TORQUE_MODE; /* scaling 1.0, offset 0.0, units none  */
	uint8_t PEDAL_STATES; /* scaling 1.0, offset 0.0, units none  */
	uint8_t SHUTDOWN_STATES; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x0c3_VCU_STATUS_t;

/* VCU analog pedal readings */
typedef PREPACK struct {
	uint16_t APPS2; /* scaling 0.0, offset 0.0, units none  */
	uint16_t BSE1; /* scaling 0.0, offset 0.0, units none  */
	uint16_t STEERING; /* scaling 0.0, offset 0.0, units none  */
	uint16_t APPS1; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x0c4_VCU_PEDAL_READINGS_t;

/* DAQ node shonk pot readings */
typedef PREPACK struct {
	uint16_t FR_shockpot; /* scaling 1.0, offset 0.0, units none  */
	uint16_t RL_shockpot; /* scaling 1.0, offset 0.0, units none  */
	uint16_t RR_shockpot; /* scaling 1.0, offset 0.0, units none  */
	uint16_t FL_shockpot; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x0c5_DAQ_SHOCKPOTS_t;

/* VCU wheel speed sensor readings */
typedef PREPACK struct {
	uint32_t RPM_FR; /* scaling 0.0, offset 0.0, units none  */
	uint32_t RPM_FL; /* scaling 0.0, offset 0.0, units none  */
} POSTPACK can_0x0c6_VCU_WHEELSPEED_READINGS_t;

/* commit hash of the firmware on the VCU */
typedef PREPACK struct {
	uint32_t fw_version; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x0c8_vcu_firmware_version_t;

/* commit hash of the firmware on the VCU */
typedef PREPACK struct {
	uint8_t dash_button5status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t dash_button4status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t dash_button3status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t dash_button2status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t dash_button1status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t dash_button6status; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x0eb_dash_buttons_t;

typedef PREPACK struct {
	uint8_t D6_14V_Monitor; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D3_HV_Input_Current; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D8_14V_Current_Monitor; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D5_DTC_Index; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D4_DTC_Status; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D7_14V_Conditional; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D2_14V_Master_Fault; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D1_HV_Input_Current_Sensor_Valid; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x1d5_M188_U2C_Message_Rxd_t;

typedef PREPACK struct {
	uint8_t D2_Setpoint_Calc; /* scaling 1.0, offset 0.0, units none  */
	uint8_t D1_ID_Byte; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x1d7_M187_U2C_Command_Txd_t;

/* Sent by BMS */
typedef PREPACK struct {
	uint16_t D2_Max_Charge_Current; /* scaling 1.0, offset 0.0, units none  */
	uint16_t D1_Max_Discharge_Current; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x202_BMS_Current_Limit_t;

/* This ID Transmits at 104 ms. */
typedef PREPACK struct {
	uint16_t Pack_CCL; /* scaling 1.0, offset 0.0, units none  */
	uint16_t Pack_DCL; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Low_Temperature; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Average_Temperature; /* scaling 1.0, offset 0.0, units none  */
	uint8_t CRC_Checksum; /* scaling 1.0, offset 0.0, units none  */
	uint8_t High_Temperature; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x6b1_MSGID_0X6B1_t;

/* This ID Transmits at 48 ms. */
typedef PREPACK struct {
	uint16_t Pack_Open_Voltage; /* scaling 0.1, offset 0.0, units none  */
	uint16_t Pack_Inst_Voltage; /* scaling 0.1, offset 0.0, units none  */
	uint16_t Pack_Summed_Voltage; /* scaling 0.0, offset 0.0, units none  */
	int16_t Pack_Current; /* scaling 0.1, offset 0.0, units none  */
} POSTPACK can_0x6b2_MSGID_0X6B2_t;

/* This ID Transmits at 1008 ms. */
typedef PREPACK struct {
	uint16_t Pack_SOC; /* scaling 0.5, offset 0.0, units none  */
	uint8_t Blank2; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Blank3; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Blank4; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Blank5; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Blank6; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Blank1; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x6b3_MSGID_0X6B3_t;

typedef PREPACK struct {
	dbcc_time_stamp_t can_0x01a_segment1_temps1_time_stamp_rx;
	dbcc_time_stamp_t can_0x01b_segment1_temps2_time_stamp_rx;
	dbcc_time_stamp_t can_0x02a_segment2_temps1_time_stamp_rx;
	dbcc_time_stamp_t can_0x02b_segment2_temps2_time_stamp_rx;
	dbcc_time_stamp_t can_0x03a_segment3_temps1_time_stamp_rx;
	dbcc_time_stamp_t can_0x03b_segment3_temps2_time_stamp_rx;
	dbcc_time_stamp_t can_0x04a_segment4_temps1_time_stamp_rx;
	dbcc_time_stamp_t can_0x04b_segment4_temps2_time_stamp_rx;
	dbcc_time_stamp_t can_0x05a_segment5_temps1_time_stamp_rx;
	dbcc_time_stamp_t can_0x05b_segment5_temps2_time_stamp_rx;
	dbcc_time_stamp_t can_0x06a_segment6_temps1_time_stamp_rx;
	dbcc_time_stamp_t can_0x06b_segment6_temps2_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a0_M160_Temperature_Set_1_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a1_M161_Temperature_Set_2_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a2_M162_Temperature_Set_3_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a3_M163_Analog_Input_Voltages_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a4_M164_Digital_Input_Status_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a5_M165_Motor_Position_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a6_M166_Current_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a7_M167_Voltage_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a8_M168_Flux_ID_IQ_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0a9_M169_Internal_Voltages_time_stamp_rx;
	dbcc_time_stamp_t can_0x0aa_M170_Internal_States_time_stamp_rx;
	dbcc_time_stamp_t can_0x0ab_M171_Fault_Codes_time_stamp_rx;
	dbcc_time_stamp_t can_0x0ac_M172_Torque_And_Timer_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0ad_M173_Modulation_And_Flux_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0ae_M174_Firmware_Info_time_stamp_rx;
	dbcc_time_stamp_t can_0x0af_M175_Diag_Data_time_stamp_rx;
	dbcc_time_stamp_t can_0x0c0_M192_Command_Message_time_stamp_rx;
	dbcc_time_stamp_t can_0x0c1_M193_Read_Write_Param_Command_time_stamp_rx;
	dbcc_time_stamp_t can_0x0c2_M194_Read_Write_Param_Response_time_stamp_rx;
	dbcc_time_stamp_t can_0x0c3_VCU_STATUS_time_stamp_rx;
	dbcc_time_stamp_t can_0x0c4_VCU_PEDAL_READINGS_time_stamp_rx;
	dbcc_time_stamp_t can_0x0c5_DAQ_SHOCKPOTS_time_stamp_rx;
	dbcc_time_stamp_t can_0x0c6_VCU_WHEELSPEED_READINGS_time_stamp_rx;
	dbcc_time_stamp_t can_0x0c8_vcu_firmware_version_time_stamp_rx;
	dbcc_time_stamp_t can_0x0eb_dash_buttons_time_stamp_rx;
	dbcc_time_stamp_t can_0x1d5_M188_U2C_Message_Rxd_time_stamp_rx;
	dbcc_time_stamp_t can_0x1d7_M187_U2C_Command_Txd_time_stamp_rx;
	dbcc_time_stamp_t can_0x202_BMS_Current_Limit_time_stamp_rx;
	dbcc_time_stamp_t can_0x6b1_MSGID_0X6B1_time_stamp_rx;
	dbcc_time_stamp_t can_0x6b2_MSGID_0X6B2_time_stamp_rx;
	dbcc_time_stamp_t can_0x6b3_MSGID_0X6B3_time_stamp_rx;
	unsigned can_0x01a_segment1_temps1_status : 2;
	unsigned can_0x01a_segment1_temps1_tx : 1;
	unsigned can_0x01a_segment1_temps1_rx : 1;
	unsigned can_0x01b_segment1_temps2_status : 2;
	unsigned can_0x01b_segment1_temps2_tx : 1;
	unsigned can_0x01b_segment1_temps2_rx : 1;
	unsigned can_0x02a_segment2_temps1_status : 2;
	unsigned can_0x02a_segment2_temps1_tx : 1;
	unsigned can_0x02a_segment2_temps1_rx : 1;
	unsigned can_0x02b_segment2_temps2_status : 2;
	unsigned can_0x02b_segment2_temps2_tx : 1;
	unsigned can_0x02b_segment2_temps2_rx : 1;
	unsigned can_0x03a_segment3_temps1_status : 2;
	unsigned can_0x03a_segment3_temps1_tx : 1;
	unsigned can_0x03a_segment3_temps1_rx : 1;
	unsigned can_0x03b_segment3_temps2_status : 2;
	unsigned can_0x03b_segment3_temps2_tx : 1;
	unsigned can_0x03b_segment3_temps2_rx : 1;
	unsigned can_0x04a_segment4_temps1_status : 2;
	unsigned can_0x04a_segment4_temps1_tx : 1;
	unsigned can_0x04a_segment4_temps1_rx : 1;
	unsigned can_0x04b_segment4_temps2_status : 2;
	unsigned can_0x04b_segment4_temps2_tx : 1;
	unsigned can_0x04b_segment4_temps2_rx : 1;
	unsigned can_0x05a_segment5_temps1_status : 2;
	unsigned can_0x05a_segment5_temps1_tx : 1;
	unsigned can_0x05a_segment5_temps1_rx : 1;
	unsigned can_0x05b_segment5_temps2_status : 2;
	unsigned can_0x05b_segment5_temps2_tx : 1;
	unsigned can_0x05b_segment5_temps2_rx : 1;
	unsigned can_0x06a_segment6_temps1_status : 2;
	unsigned can_0x06a_segment6_temps1_tx : 1;
	unsigned can_0x06a_segment6_temps1_rx : 1;
	unsigned can_0x06b_segment6_temps2_status : 2;
	unsigned can_0x06b_segment6_temps2_tx : 1;
	unsigned can_0x06b_segment6_temps2_rx : 1;
	unsigned can_0x0a0_M160_Temperature_Set_1_status : 2;
	unsigned can_0x0a0_M160_Temperature_Set_1_tx : 1;
	unsigned can_0x0a0_M160_Temperature_Set_1_rx : 1;
	unsigned can_0x0a1_M161_Temperature_Set_2_status : 2;
	unsigned can_0x0a1_M161_Temperature_Set_2_tx : 1;
	unsigned can_0x0a1_M161_Temperature_Set_2_rx : 1;
	unsigned can_0x0a2_M162_Temperature_Set_3_status : 2;
	unsigned can_0x0a2_M162_Temperature_Set_3_tx : 1;
	unsigned can_0x0a2_M162_Temperature_Set_3_rx : 1;
	unsigned can_0x0a3_M163_Analog_Input_Voltages_status : 2;
	unsigned can_0x0a3_M163_Analog_Input_Voltages_tx : 1;
	unsigned can_0x0a3_M163_Analog_Input_Voltages_rx : 1;
	unsigned can_0x0a4_M164_Digital_Input_Status_status : 2;
	unsigned can_0x0a4_M164_Digital_Input_Status_tx : 1;
	unsigned can_0x0a4_M164_Digital_Input_Status_rx : 1;
	unsigned can_0x0a5_M165_Motor_Position_Info_status : 2;
	unsigned can_0x0a5_M165_Motor_Position_Info_tx : 1;
	unsigned can_0x0a5_M165_Motor_Position_Info_rx : 1;
	unsigned can_0x0a6_M166_Current_Info_status : 2;
	unsigned can_0x0a6_M166_Current_Info_tx : 1;
	unsigned can_0x0a6_M166_Current_Info_rx : 1;
	unsigned can_0x0a7_M167_Voltage_Info_status : 2;
	unsigned can_0x0a7_M167_Voltage_Info_tx : 1;
	unsigned can_0x0a7_M167_Voltage_Info_rx : 1;
	unsigned can_0x0a8_M168_Flux_ID_IQ_Info_status : 2;
	unsigned can_0x0a8_M168_Flux_ID_IQ_Info_tx : 1;
	unsigned can_0x0a8_M168_Flux_ID_IQ_Info_rx : 1;
	unsigned can_0x0a9_M169_Internal_Voltages_status : 2;
	unsigned can_0x0a9_M169_Internal_Voltages_tx : 1;
	unsigned can_0x0a9_M169_Internal_Voltages_rx : 1;
	unsigned can_0x0aa_M170_Internal_States_status : 2;
	unsigned can_0x0aa_M170_Internal_States_tx : 1;
	unsigned can_0x0aa_M170_Internal_States_rx : 1;
	unsigned can_0x0ab_M171_Fault_Codes_status : 2;
	unsigned can_0x0ab_M171_Fault_Codes_tx : 1;
	unsigned can_0x0ab_M171_Fault_Codes_rx : 1;
	unsigned can_0x0ac_M172_Torque_And_Timer_Info_status : 2;
	unsigned can_0x0ac_M172_Torque_And_Timer_Info_tx : 1;
	unsigned can_0x0ac_M172_Torque_And_Timer_Info_rx : 1;
	unsigned can_0x0ad_M173_Modulation_And_Flux_Info_status : 2;
	unsigned can_0x0ad_M173_Modulation_And_Flux_Info_tx : 1;
	unsigned can_0x0ad_M173_Modulation_And_Flux_Info_rx : 1;
	unsigned can_0x0ae_M174_Firmware_Info_status : 2;
	unsigned can_0x0ae_M174_Firmware_Info_tx : 1;
	unsigned can_0x0ae_M174_Firmware_Info_rx : 1;
	unsigned can_0x0af_M175_Diag_Data_status : 2;
	unsigned can_0x0af_M175_Diag_Data_tx : 1;
	unsigned can_0x0af_M175_Diag_Data_rx : 1;
	unsigned can_0x0c0_M192_Command_Message_status : 2;
	unsigned can_0x0c0_M192_Command_Message_tx : 1;
	unsigned can_0x0c0_M192_Command_Message_rx : 1;
	unsigned can_0x0c1_M193_Read_Write_Param_Command_status : 2;
	unsigned can_0x0c1_M193_Read_Write_Param_Command_tx : 1;
	unsigned can_0x0c1_M193_Read_Write_Param_Command_rx : 1;
	unsigned can_0x0c2_M194_Read_Write_Param_Response_status : 2;
	unsigned can_0x0c2_M194_Read_Write_Param_Response_tx : 1;
	unsigned can_0x0c2_M194_Read_Write_Param_Response_rx : 1;
	unsigned can_0x0c3_VCU_STATUS_status : 2;
	unsigned can_0x0c3_VCU_STATUS_tx : 1;
	unsigned can_0x0c3_VCU_STATUS_rx : 1;
	unsigned can_0x0c4_VCU_PEDAL_READINGS_status : 2;
	unsigned can_0x0c4_VCU_PEDAL_READINGS_tx : 1;
	unsigned can_0x0c4_VCU_PEDAL_READINGS_rx : 1;
	unsigned can_0x0c5_DAQ_SHOCKPOTS_status : 2;
	unsigned can_0x0c5_DAQ_SHOCKPOTS_tx : 1;
	unsigned can_0x0c5_DAQ_SHOCKPOTS_rx : 1;
	unsigned can_0x0c6_VCU_WHEELSPEED_READINGS_status : 2;
	unsigned can_0x0c6_VCU_WHEELSPEED_READINGS_tx : 1;
	unsigned can_0x0c6_VCU_WHEELSPEED_READINGS_rx : 1;
	unsigned can_0x0c8_vcu_firmware_version_status : 2;
	unsigned can_0x0c8_vcu_firmware_version_tx : 1;
	unsigned can_0x0c8_vcu_firmware_version_rx : 1;
	unsigned can_0x0eb_dash_buttons_status : 2;
	unsigned can_0x0eb_dash_buttons_tx : 1;
	unsigned can_0x0eb_dash_buttons_rx : 1;
	unsigned can_0x1d5_M188_U2C_Message_Rxd_status : 2;
	unsigned can_0x1d5_M188_U2C_Message_Rxd_tx : 1;
	unsigned can_0x1d5_M188_U2C_Message_Rxd_rx : 1;
	unsigned can_0x1d7_M187_U2C_Command_Txd_status : 2;
	unsigned can_0x1d7_M187_U2C_Command_Txd_tx : 1;
	unsigned can_0x1d7_M187_U2C_Command_Txd_rx : 1;
	unsigned can_0x202_BMS_Current_Limit_status : 2;
	unsigned can_0x202_BMS_Current_Limit_tx : 1;
	unsigned can_0x202_BMS_Current_Limit_rx : 1;
	unsigned can_0x6b1_MSGID_0X6B1_status : 2;
	unsigned can_0x6b1_MSGID_0X6B1_tx : 1;
	unsigned can_0x6b1_MSGID_0X6B1_rx : 1;
	unsigned can_0x6b2_MSGID_0X6B2_status : 2;
	unsigned can_0x6b2_MSGID_0X6B2_tx : 1;
	unsigned can_0x6b2_MSGID_0X6B2_rx : 1;
	unsigned can_0x6b3_MSGID_0X6B3_status : 2;
	unsigned can_0x6b3_MSGID_0X6B3_tx : 1;
	unsigned can_0x6b3_MSGID_0X6B3_rx : 1;
	can_0x01a_segment1_temps1_t can_0x01a_segment1_temps1;
	can_0x01b_segment1_temps2_t can_0x01b_segment1_temps2;
	can_0x02a_segment2_temps1_t can_0x02a_segment2_temps1;
	can_0x02b_segment2_temps2_t can_0x02b_segment2_temps2;
	can_0x03a_segment3_temps1_t can_0x03a_segment3_temps1;
	can_0x03b_segment3_temps2_t can_0x03b_segment3_temps2;
	can_0x04a_segment4_temps1_t can_0x04a_segment4_temps1;
	can_0x04b_segment4_temps2_t can_0x04b_segment4_temps2;
	can_0x05a_segment5_temps1_t can_0x05a_segment5_temps1;
	can_0x05b_segment5_temps2_t can_0x05b_segment5_temps2;
	can_0x06a_segment6_temps1_t can_0x06a_segment6_temps1;
	can_0x06b_segment6_temps2_t can_0x06b_segment6_temps2;
	can_0x0a0_M160_Temperature_Set_1_t can_0x0a0_M160_Temperature_Set_1;
	can_0x0a1_M161_Temperature_Set_2_t can_0x0a1_M161_Temperature_Set_2;
	can_0x0a2_M162_Temperature_Set_3_t can_0x0a2_M162_Temperature_Set_3;
	can_0x0a3_M163_Analog_Input_Voltages_t can_0x0a3_M163_Analog_Input_Voltages;
	can_0x0a4_M164_Digital_Input_Status_t can_0x0a4_M164_Digital_Input_Status;
	can_0x0a5_M165_Motor_Position_Info_t can_0x0a5_M165_Motor_Position_Info;
	can_0x0a6_M166_Current_Info_t can_0x0a6_M166_Current_Info;
	can_0x0a7_M167_Voltage_Info_t can_0x0a7_M167_Voltage_Info;
	can_0x0a8_M168_Flux_ID_IQ_Info_t can_0x0a8_M168_Flux_ID_IQ_Info;
	can_0x0a9_M169_Internal_Voltages_t can_0x0a9_M169_Internal_Voltages;
	can_0x0aa_M170_Internal_States_t can_0x0aa_M170_Internal_States;
	can_0x0ab_M171_Fault_Codes_t can_0x0ab_M171_Fault_Codes;
	can_0x0ac_M172_Torque_And_Timer_Info_t can_0x0ac_M172_Torque_And_Timer_Info;
	can_0x0ad_M173_Modulation_And_Flux_Info_t can_0x0ad_M173_Modulation_And_Flux_Info;
	can_0x0ae_M174_Firmware_Info_t can_0x0ae_M174_Firmware_Info;
	can_0x0af_M175_Diag_Data_t can_0x0af_M175_Diag_Data;
	can_0x0c0_M192_Command_Message_t can_0x0c0_M192_Command_Message;
	can_0x0c1_M193_Read_Write_Param_Command_t can_0x0c1_M193_Read_Write_Param_Command;
	can_0x0c2_M194_Read_Write_Param_Response_t can_0x0c2_M194_Read_Write_Param_Response;
	can_0x0c3_VCU_STATUS_t can_0x0c3_VCU_STATUS;
	can_0x0c4_VCU_PEDAL_READINGS_t can_0x0c4_VCU_PEDAL_READINGS;
	can_0x0c5_DAQ_SHOCKPOTS_t can_0x0c5_DAQ_SHOCKPOTS;
	can_0x0c6_VCU_WHEELSPEED_READINGS_t can_0x0c6_VCU_WHEELSPEED_READINGS;
	can_0x0c8_vcu_firmware_version_t can_0x0c8_vcu_firmware_version;
	can_0x0eb_dash_buttons_t can_0x0eb_dash_buttons;
	can_0x1d5_M188_U2C_Message_Rxd_t can_0x1d5_M188_U2C_Message_Rxd;
	can_0x1d7_M187_U2C_Command_Txd_t can_0x1d7_M187_U2C_Command_Txd;
	can_0x202_BMS_Current_Limit_t can_0x202_BMS_Current_Limit;
	can_0x6b1_MSGID_0X6B1_t can_0x6b1_MSGID_0X6B1;
	can_0x6b2_MSGID_0X6B2_t can_0x6b2_MSGID_0X6B2;
	can_0x6b3_MSGID_0X6B3_t can_0x6b3_MSGID_0X6B3;
} POSTPACK can_obj_ksu_dbc_h_t;

int unpack_message(can_obj_ksu_dbc_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp);
int pack_message(can_obj_ksu_dbc_h_t *o, const unsigned long id, uint64_t *data);
int print_message(const can_obj_ksu_dbc_h_t *o, const unsigned long id, FILE *output);

int decode_can_0x01a_cell2temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01a_cell2temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x01a_cell3temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01a_cell3temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x01a_cell4temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01a_cell4temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x01a_cell5temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01a_cell5temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x01a_cell6temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01a_cell6temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x01a_mintemp1to6(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01a_mintemp1to6(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x01a_maxtemp1to6(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01a_maxtemp1to6(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x01a_cell1temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01a_cell1temp(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x01b_cell8temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01b_cell8temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x01b_cell9temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01b_cell9temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x01b_cell10temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01b_cell10temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x01b_cell11temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01b_cell11temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x01b_cell12temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01b_cell12temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x01b_mintemp7to12(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01b_mintemp7to12(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x01b_maxtemp7to12(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01b_maxtemp7to12(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x01b_cell7temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x01b_cell7temp(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x02a_cell14temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02a_cell14temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x02a_cell15temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02a_cell15temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x02a_cell16temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02a_cell16temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x02a_cell17temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02a_cell17temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x02a_cell18temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02a_cell18temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x02a_mintemp13to18(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02a_mintemp13to18(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x02a_maxtemp13to18(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02a_maxtemp13to18(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x02a_cell13temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02a_cell13temp(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x02b_cell20temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02b_cell20temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x02b_cell21temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02b_cell21temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x02b_cell22temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02b_cell22temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x02b_cell23temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02b_cell23temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x02b_cell24temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02b_cell24temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x02b_mintemp19to24(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02b_mintemp19to24(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x02b_maxtemp19to24(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02b_maxtemp19to24(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x02b_cell19temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x02b_cell19temp(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x03a_cell26temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03a_cell26temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x03a_cell27temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03a_cell27temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x03a_cell28temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03a_cell28temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x03a_cell29temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03a_cell29temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x03a_cell30temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03a_cell30temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x03a_mintemp25to30(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03a_mintemp25to30(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x03a_maxtemp25to30(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03a_maxtemp25to30(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x03a_cell25temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03a_cell25temp(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x03b_cell32temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03b_cell32temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x03b_cell33temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03b_cell33temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x03b_cell34temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03b_cell34temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x03b_cell35temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03b_cell35temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x03b_cell36temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03b_cell36temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x03b_mintemp31to36(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03b_mintemp31to36(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x03b_maxtemp31to36(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03b_maxtemp31to36(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x03b_cell31temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x03b_cell31temp(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x04a_cell38temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04a_cell38temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x04a_cell39temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04a_cell39temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x04a_cell40temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04a_cell40temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x04a_cell41temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04a_cell41temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x04a_cell42temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04a_cell42temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x04a_mintemp37to42(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04a_mintemp37to42(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x04a_maxtemp37to42(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04a_maxtemp37to42(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x04a_cell37temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04a_cell37temp(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x04b_cell44temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04b_cell44temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x04b_cell45temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04b_cell45temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x04b_cell46temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04b_cell46temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x04b_cell47temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04b_cell47temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x04b_cell48temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04b_cell48temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x04b_mintemp43to48(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04b_mintemp43to48(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x04b_maxtemp43to48(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04b_maxtemp43to48(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x04b_cell43temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x04b_cell43temp(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x05a_cell50temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05a_cell50temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x05a_cell51temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05a_cell51temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x05a_cell52temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05a_cell52temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x05a_cell53temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05a_cell53temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x05a_cell54temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05a_cell54temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x05a_mintemp49to54(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05a_mintemp49to54(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x05a_maxtemp49to54(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05a_maxtemp49to54(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x05a_cell49temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05a_cell49temp(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x05b_cell56temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05b_cell56temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x05b_cell57temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05b_cell57temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x05b_cell58temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05b_cell58temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x05b_cell59temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05b_cell59temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x05b_cell60temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05b_cell60temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x05b_mintemp55to60(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05b_mintemp55to60(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x05b_maxtemp55to60(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05b_maxtemp55to60(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x05b_cell55temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x05b_cell55temp(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x06a_cell62temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06a_cell62temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x06a_cell63temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06a_cell63temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x06a_cell64temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06a_cell64temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x06a_cell65temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06a_cell65temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x06a_cell66temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06a_cell66temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x06a_mintemp61to66(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06a_mintemp61to66(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x06a_maxtemp61to66(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06a_maxtemp61to66(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x06a_cell61temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06a_cell61temp(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x06b_cell68temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06b_cell68temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x06b_cell69temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06b_cell69temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x06b_cell70temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06b_cell70temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x06b_cell71temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06b_cell71temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x06b_cell72temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06b_cell72temp(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x06b_mintemp67to72(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06b_mintemp67to72(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x06b_maxtemp67to72(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06b_maxtemp67to72(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x06b_cell67temp(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x06b_cell67temp(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x0a0_D2_Module_B(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a0_D2_Module_B(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a0_D3_Module_C(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a0_D3_Module_C(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a0_D4_Gate_Driver_Board(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a0_D4_Gate_Driver_Board(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a0_D1_Module_A(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a0_D1_Module_A(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x0a1_D2_RTD1_Temperature(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a1_D2_RTD1_Temperature(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a1_D3_RTD2_Temperature(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a1_D3_RTD2_Temperature(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a1_D4_RTD3_Temperature(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a1_D4_RTD3_Temperature(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a1_D1_Control_Board_Temperature(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a1_D1_Control_Board_Temperature(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x0a2_D2_RTD5_Temperature(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a2_D2_RTD5_Temperature(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a2_D3_Motor_Temperature(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a2_D3_Motor_Temperature(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a2_D4_Torque_Shudder(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a2_D4_Torque_Shudder(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a2_D1_RTD4_Temperature(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a2_D1_RTD4_Temperature(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x0a3_D2_Analog_Input_2(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a3_D2_Analog_Input_2(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a3_D3_Analog_Input_3(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a3_D3_Analog_Input_3(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a3_D4_Analog_Input_4(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a3_D4_Analog_Input_4(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a3_D5_Analog_Input_5(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a3_D5_Analog_Input_5(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a3_D6_Analog_Input_6(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a3_D6_Analog_Input_6(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a3_D1_Analog_Input_1(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a3_D1_Analog_Input_1(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x0a4_D2_Digital_Input_2(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0a4_D2_Digital_Input_2(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0a4_D3_Digital_Input_3(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0a4_D3_Digital_Input_3(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0a4_D4_Digital_Input_4(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0a4_D4_Digital_Input_4(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0a4_D5_Digital_Input_5(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0a4_D5_Digital_Input_5(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0a4_D6_Digital_Input_6(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0a4_D6_Digital_Input_6(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0a4_D7_Digital_Input_7(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0a4_D7_Digital_Input_7(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0a4_D8_Digital_Input_8(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0a4_D8_Digital_Input_8(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0a4_D1_Digital_Input_1(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0a4_D1_Digital_Input_1(can_obj_ksu_dbc_h_t *o, uint8_t in);


int decode_can_0x0a5_D2_Motor_Speed(const can_obj_ksu_dbc_h_t *o, int16_t *out);
int encode_can_0x0a5_D2_Motor_Speed(can_obj_ksu_dbc_h_t *o, int16_t in);
int decode_can_0x0a5_D3_Electrical_Output_Frequency(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a5_D3_Electrical_Output_Frequency(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a5_D4_Delta_Resolver_Filtered(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a5_D4_Delta_Resolver_Filtered(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a5_D1_Motor_Angle_Electrical(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a5_D1_Motor_Angle_Electrical(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x0a6_D2_Phase_B_Current(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a6_D2_Phase_B_Current(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a6_D3_Phase_C_Current(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a6_D3_Phase_C_Current(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a6_D4_DC_Bus_Current(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a6_D4_DC_Bus_Current(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a6_D1_Phase_A_Current(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a6_D1_Phase_A_Current(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x0a7_D2_Output_Voltage(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a7_D2_Output_Voltage(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a7_D3_VAB_Vd_Voltage(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a7_D3_VAB_Vd_Voltage(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a7_D4_VBC_Vq_Voltage(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a7_D4_VBC_Vq_Voltage(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a7_D1_DC_Bus_Voltage(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a7_D1_DC_Bus_Voltage(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x0a8_D2_Flux_Feedback(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a8_D2_Flux_Feedback(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a8_D3_Id(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a8_D3_Id(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a8_D4_Iq(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a8_D4_Iq(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a8_D1_Flux_Command(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a8_D1_Flux_Command(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x0a9_D2_Reference_Voltage_2_5(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a9_D2_Reference_Voltage_2_5(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a9_D3_Reference_Voltage_5_0(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a9_D3_Reference_Voltage_5_0(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a9_D4_Reference_Voltage_12_0(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a9_D4_Reference_Voltage_12_0(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0a9_D1_Reference_Voltage_1_5(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0a9_D1_Reference_Voltage_1_5(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x0aa_D1_VSM_State(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0aa_D1_VSM_State(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x0aa_D2_Inverter_State(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D2_Inverter_State(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0aa_D4_Inverter_Discharge_State(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D4_Inverter_Discharge_State(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0aa_D3_Relay_3_Status(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D3_Relay_3_Status(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0aa_D3_Relay_1_Status(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D3_Relay_1_Status(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0aa_D3_Relay_5_Status(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D3_Relay_5_Status(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0aa_D3_Relay_6_Status(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D3_Relay_6_Status(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0aa_D4_Inverter_Run_Mode(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D4_Inverter_Run_Mode(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0aa_D3_Relay_4_Status(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D3_Relay_4_Status(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0aa_D3_Relay_2_Status(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D3_Relay_2_Status(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0aa_D5_Inverter_Command_Mode(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D5_Inverter_Command_Mode(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0aa_D6_Inverter_Enable_State(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D6_Inverter_Enable_State(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0aa_D6_Inverter_Enable_Lockout(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D6_Inverter_Enable_Lockout(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0aa_D7_Direction_Command(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D7_Direction_Command(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0aa_D7_BMS_Active(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D7_BMS_Active(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0aa_D7_BMS_Torque_Limiting(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0aa_D7_BMS_Torque_Limiting(can_obj_ksu_dbc_h_t *o, uint8_t in);


int decode_can_0x0ab_D2_Post_Fault_Hi(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0ab_D2_Post_Fault_Hi(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x0ab_D3_Run_Fault_Lo(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0ab_D3_Run_Fault_Lo(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x0ab_D4_Run_Fault_Hi(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0ab_D4_Run_Fault_Hi(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x0ab_D1_Post_Fault_Lo(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0ab_D1_Post_Fault_Lo(can_obj_ksu_dbc_h_t *o, uint16_t in);


int decode_can_0x0ac_D3_Power_On_Timer(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0ac_D3_Power_On_Timer(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0ac_D2_Torque_Feedback(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0ac_D2_Torque_Feedback(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0ac_D1_Commanded_Torque(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0ac_D1_Commanded_Torque(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x0ad_D2_Flux_Weakening_Output(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0ad_D2_Flux_Weakening_Output(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0ad_D3_Id_Command(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0ad_D3_Id_Command(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0ad_D4_Iq_Command(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0ad_D4_Iq_Command(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0ad_D1_Modulation_Index(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0ad_D1_Modulation_Index(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x0ae_D2_SW_Version(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0ae_D2_SW_Version(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x0ae_D3_DateCode_MMDD(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0ae_D3_DateCode_MMDD(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x0ae_D4_DateCode_YYYY(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0ae_D4_DateCode_YYYY(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x0ae_D1_Project_Code_EEP_Ver(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0ae_D1_Project_Code_EEP_Ver(can_obj_ksu_dbc_h_t *o, uint16_t in);


int decode_can_0x0af_D4_Diag_Data_2(const can_obj_ksu_dbc_h_t *o, int16_t *out);
int encode_can_0x0af_D4_Diag_Data_2(can_obj_ksu_dbc_h_t *o, int16_t in);
int decode_can_0x0af_D3_Diag_Data_1(const can_obj_ksu_dbc_h_t *o, int16_t *out);
int encode_can_0x0af_D3_Diag_Data_1(can_obj_ksu_dbc_h_t *o, int16_t in);
int decode_can_0x0af_D5_Diag_Data_3(const can_obj_ksu_dbc_h_t *o, int16_t *out);
int encode_can_0x0af_D5_Diag_Data_3(can_obj_ksu_dbc_h_t *o, int16_t in);
int decode_can_0x0af_D2_Buffer_Segment(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0af_D2_Buffer_Segment(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0af_D1_Buffer_Record(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0af_D1_Buffer_Record(can_obj_ksu_dbc_h_t *o, uint8_t in);


int decode_can_0x0c0_Speed_Command(const can_obj_ksu_dbc_h_t *o, int16_t *out);
int encode_can_0x0c0_Speed_Command(can_obj_ksu_dbc_h_t *o, int16_t in);
int decode_can_0x0c0_Torque_Limit_Command(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0c0_Torque_Limit_Command(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0c0_Torque_Command(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0c0_Torque_Command(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0c0_Inverter_Discharge(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0c0_Inverter_Discharge(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0c0_Speed_Mode_Enable(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0c0_Speed_Mode_Enable(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0c0_Inverter_Enable(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0c0_Inverter_Enable(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0c0_Direction_Command(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0c0_Direction_Command(can_obj_ksu_dbc_h_t *o, uint8_t in);


int decode_can_0x0c1_D3_Data_Command(const can_obj_ksu_dbc_h_t *o, int16_t *out);
int encode_can_0x0c1_D3_Data_Command(can_obj_ksu_dbc_h_t *o, int16_t in);
int decode_can_0x0c1_D1_Parameter_Address_Command(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0c1_D1_Parameter_Address_Command(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x0c1_D2_Read_Write_Command(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0c1_D2_Read_Write_Command(can_obj_ksu_dbc_h_t *o, uint8_t in);


int decode_can_0x0c2_D3_Data_Response(const can_obj_ksu_dbc_h_t *o, int16_t *out);
int encode_can_0x0c2_D3_Data_Response(can_obj_ksu_dbc_h_t *o, int16_t in);
int decode_can_0x0c2_D1_Parameter_Address_Response(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0c2_D1_Parameter_Address_Response(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x0c2_D2_Write_Success(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0c2_D2_Write_Success(can_obj_ksu_dbc_h_t *o, uint8_t in);


int decode_can_0x0c3_DISTANCE_TRAVELLED(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0c3_DISTANCE_TRAVELLED(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x0c3_ECU_STATES(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0c3_ECU_STATES(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0c3_MAX_TORQUE(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0c3_MAX_TORQUE(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0c3_TORQUE_MODE(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0c3_TORQUE_MODE(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0c3_PEDAL_STATES(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0c3_PEDAL_STATES(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0c3_SHUTDOWN_STATES(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0c3_SHUTDOWN_STATES(can_obj_ksu_dbc_h_t *o, uint8_t in);


int decode_can_0x0c4_APPS2(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0c4_APPS2(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0c4_BSE1(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0c4_BSE1(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0c4_STEERING(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0c4_STEERING(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0c4_APPS1(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0c4_APPS1(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x0c5_FR_shockpot(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0c5_FR_shockpot(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x0c5_RL_shockpot(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0c5_RL_shockpot(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x0c5_RR_shockpot(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0c5_RR_shockpot(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x0c5_FL_shockpot(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x0c5_FL_shockpot(can_obj_ksu_dbc_h_t *o, uint16_t in);


int decode_can_0x0c6_RPM_FR(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0c6_RPM_FR(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x0c6_RPM_FL(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x0c6_RPM_FL(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x0c8_fw_version(const can_obj_ksu_dbc_h_t *o, uint32_t *out);
int encode_can_0x0c8_fw_version(can_obj_ksu_dbc_h_t *o, uint32_t in);


int decode_can_0x0eb_dash_button5status(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0eb_dash_button5status(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0eb_dash_button4status(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0eb_dash_button4status(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0eb_dash_button3status(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0eb_dash_button3status(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0eb_dash_button2status(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0eb_dash_button2status(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0eb_dash_button1status(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0eb_dash_button1status(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x0eb_dash_button6status(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x0eb_dash_button6status(can_obj_ksu_dbc_h_t *o, uint8_t in);


int decode_can_0x1d5_D6_14V_Monitor(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x1d5_D6_14V_Monitor(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x1d5_D3_HV_Input_Current(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x1d5_D3_HV_Input_Current(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x1d5_D8_14V_Current_Monitor(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x1d5_D8_14V_Current_Monitor(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x1d5_D5_DTC_Index(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x1d5_D5_DTC_Index(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x1d5_D4_DTC_Status(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x1d5_D4_DTC_Status(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x1d5_D7_14V_Conditional(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x1d5_D7_14V_Conditional(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x1d5_D2_14V_Master_Fault(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x1d5_D2_14V_Master_Fault(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x1d5_D1_HV_Input_Current_Sensor_Valid(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x1d5_D1_HV_Input_Current_Sensor_Valid(can_obj_ksu_dbc_h_t *o, uint8_t in);


int decode_can_0x1d7_D2_Setpoint_Calc(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x1d7_D2_Setpoint_Calc(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x1d7_D1_ID_Byte(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x1d7_D1_ID_Byte(can_obj_ksu_dbc_h_t *o, uint8_t in);


int decode_can_0x202_D2_Max_Charge_Current(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x202_D2_Max_Charge_Current(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x202_D1_Max_Discharge_Current(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x202_D1_Max_Discharge_Current(can_obj_ksu_dbc_h_t *o, uint16_t in);


int decode_can_0x6b1_Pack_CCL(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x6b1_Pack_CCL(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x6b1_Pack_DCL(const can_obj_ksu_dbc_h_t *o, uint16_t *out);
int encode_can_0x6b1_Pack_DCL(can_obj_ksu_dbc_h_t *o, uint16_t in);
int decode_can_0x6b1_Low_Temperature(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x6b1_Low_Temperature(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x6b1_Average_Temperature(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x6b1_Average_Temperature(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x6b1_CRC_Checksum(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x6b1_CRC_Checksum(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x6b1_High_Temperature(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x6b1_High_Temperature(can_obj_ksu_dbc_h_t *o, uint8_t in);


int decode_can_0x6b2_Pack_Open_Voltage(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x6b2_Pack_Open_Voltage(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x6b2_Pack_Inst_Voltage(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x6b2_Pack_Inst_Voltage(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x6b2_Pack_Summed_Voltage(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x6b2_Pack_Summed_Voltage(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x6b2_Pack_Current(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x6b2_Pack_Current(can_obj_ksu_dbc_h_t *o, double in);


int decode_can_0x6b3_Pack_SOC(const can_obj_ksu_dbc_h_t *o, double *out);
int encode_can_0x6b3_Pack_SOC(can_obj_ksu_dbc_h_t *o, double in);
int decode_can_0x6b3_Blank2(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x6b3_Blank2(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x6b3_Blank3(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x6b3_Blank3(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x6b3_Blank4(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x6b3_Blank4(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x6b3_Blank5(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x6b3_Blank5(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x6b3_Blank6(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x6b3_Blank6(can_obj_ksu_dbc_h_t *o, uint8_t in);
int decode_can_0x6b3_Blank1(const can_obj_ksu_dbc_h_t *o, uint8_t *out);
int encode_can_0x6b3_Blank1(can_obj_ksu_dbc_h_t *o, uint8_t in);


#ifdef __cplusplus
} 
#endif

#endif
